language: go

matrix:
  include:
    - os: linux
      go: "1.11.x"
    - os: osx
      go: "1.11.x"
    - os: windows
      go: "1.11.x"

  
script:
  - GO111MODULE=on go test ./... 
  - GO111MODULE=on go test -v ./...
  
